version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - run:
          name : Login docker
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Build docker image
          command: docker build -t spanglishing/kafka-push:$CIRCLE_SHA1 .
      - run:
          name: Push docker image
          command: docker push spanglishing/kafka-push:$CIRCLE_SHA1