version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name : Login docker
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Build docker image
          command: docker build -t spanglishing/kafka-push:$CIRCLE_BUILD_NUM .
      - run:
          name: Push docker image
          command: docker push spanglishing/kafka-push:$CIRCLE_BUILD_NUM
workflows:
  version: 2
  workflow:
    jobs:
      - build