version: 2
jobs:
  build:
    machine: golang:1.9
    steps:
      - checkout
      - run:
          name: Directory app
          command: cd app
      - run:
          name: Build app
          command: go test -mod=vendor -v ./...
      - run:
          name : Login docker
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Build docker image
          command: docker build -t spanglishing/kafka-push:$CIRCLE_SHA1 .
      - run:
          name: Push docker image
          command: docker push spanglishing/kafka-push:$CIRCLE_SHA1